### ISSUE TITLE
ptctl fails when using spi.cshigh

### ISSUE THREAD

**Issue by ghost** [jaylittle/pi-top-control#1]
with Linux 5.4.72 `ptctl.py system off` gives the cryptic error of "SystemError: error return without exception set"

From reading https://github.com/raspberrypi/linux/issues/3745 and https://github.com/doceme/py-spidev/issues/106 it seems like `spi.cshigh` isn't really supported. 
attempted to just remove the places where `spi.cshigh`  gets set. This didn't give errors but got stuck in a loop and didn't seem to do anything

**Comment by jaylittle** [comment]
Thanks for your interest, but at this time I'm no longer actively maintaining this codebase as I no longer have a pi-top to test against.  I will update the README appropriately.  However I did DuckDuckGo some interesting information you might find useful:

https://github.com/raspberrypi/linux/issues/3355

Based on reading that alone, this is definitely a kernel level bug.  In addition the pi-top repo has a small PR on this which reconfirms that.

https://github.com/pi-top/pi-topHUB-v1/pull/5

**Comment by ghost** [comment]
ok, thanks for the info. Judging by the last commit date I suspected that this project was not currently being worked on. Thanks for the prompt response.
